[storage]
driver = "overlay"

[storage.options]
# move image storage off your home dir if it's on a small partition
# graphRoot = "/data/containers/storage"

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"  # needed on some systems

